a = int(input("first number: "))
b = int(input("second number: "))
print(f"result of {a} + {b} is {a + b}")
print(f"result of {a} - {b} is {a - b}")
print(f"result of {a} * {b} is {a * b}")
print(f"result of {a} / {b} is {a / b}")
